/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import roman_numerals.Roman;

import static org.junit.Assert.*;

public class RomanOfShould {
    @Test public void convertArabicNumbersToRoman() {
        assertEquals("", Roman.of(0));
        assertEquals("I", Roman.of(1));
        assertEquals("II", Roman.of(2));
        assertEquals("III", Roman.of(3));
        assertEquals("V", Roman.of(5));
        assertEquals("VI", Roman.of(6));
        assertEquals("VII", Roman.of(7));
        assertEquals("X", Roman.of(10));
        assertEquals("XVII", Roman.of(17));
        assertEquals("XXV", Roman.of(25));
        assertEquals("IV", Roman.of(4));
        assertEquals("IX", Roman.of(9));
        assertEquals("XL", Roman.of(40));
        assertEquals("L", Roman.of(50));
        assertEquals("XC", Roman.of(90));
        assertEquals("C", Roman.of(100));
        assertEquals("CD", Roman.of(400));
        assertEquals("D", Roman.of(500));
        assertEquals("CM", Roman.of(900));
        assertEquals("M", Roman.of(1000));
        assertEquals("MMMMDLXIX", Roman.of(4569));
        assertEquals("MMMMCMXCIX", Roman.of(4999));
    }
}
