import roman_numerals.Roman;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        System.out.print("Introduce arabic number: ");
        Scanner scanner = new Scanner(System.in);
        var arabic = scanner.nextInt();
        System.out.println("\nRoman of " + arabic + " is " + Roman.of(arabic));
    }
}
